//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.email", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for joining MAJESTA Treesponsible™ News and the movement to plant more trees. You will soon begin receiving information, rewards and savings absolutely free. 
        ///&lt;br /&gt;&lt;br /&gt;
        ///Have you received this message in error? To be removed from the Treesponsible™ News Community just &lt;a href=&quot;[[ServerURL]]/Unsubscribe.aspx?email=[[uemail]]&quot;&gt;click here&lt;/a&gt;.
        ///&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string MajestaBody {
            get {
                return ResourceManager.GetString("MajestaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreesponsibleNews@majestapromotions.ca.
        /// </summary>
        internal static string MajestaEmail {
            get {
                return ResourceManager.GetString("MajestaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///        &lt;td bgcolor=&quot;#faddea&quot; style=&quot;background-color:#faddea;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///    	&lt;td width=&quot;11&quot; height=&quot;11&quot; bgcolor=&quot;#faddea&quot; style=&quot;background-color:#faddea;&quot;&gt;&lt;img src=&quot;http://majesta.com/uploadedImages/email-images/TreesponsibleNews/majesta_email_corner_bl.jpg&quot; alt=&quot;&quot; width=&quot;11&quot; height=&quot;11&quot;&gt;&lt;/td&gt;
        ///        &lt;td bgcolor=&quot;#faddea&quot; style=&quot;background-color:#faddea;&quot;&gt;&lt;font style=&quot;font-size:5px; font-family:Arial, Helvetica, sans-serif&quot;&gt;&amp;nbsp;&lt;/font&gt;&lt;/td&gt;
        ///    	&lt;td width=&quot;11&quot; height=&quot;11&quot; bg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MajestaFooter {
            get {
                return ResourceManager.GetString("MajestaFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body bgcolor=&quot;#fff&quot; bottommargin=&quot;0&quot; topmargin=&quot;0&quot; leftmargin=&quot;0&quot; rightmargin=&quot;0&quot;&gt;&lt;br /&gt;
        ///&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#ffffff&quot; width=&quot;600&quot; align=&quot;center&quot;&gt;&lt;tbody&gt;
        ///&lt;tr&gt;
        ///  &lt;td&gt;&lt;img height=&quot;150&quot; width=&quot;600&quot; src=&quot;http://majesta.com/uploadedImages/email-images/TreesponsibleNews/emailHeader-en.gif&quot; alt=&quot;&quot;&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td style=&quot;padding:10px 6px 10px 6px;&quot;&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; width=&quot;588&quot; bgcolor=&quot;#faddea&quot; style=&quot;background-color:#faddea;&quot;&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MajestaHeader {
            get {
                return ResourceManager.GetString("MajestaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome from MAJESTA.
        /// </summary>
        internal static string MajestaSubjectLine {
            get {
                return ResourceManager.GetString("MajestaSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://majestapromotions.ca/.
        /// </summary>
        internal static string MajestaUrl {
            get {
                return ResourceManager.GetString("MajestaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for joining Moment with ROYALE. You will soon begin receiving news, rewards and savings absolutely free. From time to time you will also receive exclusive offers from ROYALE as part of your membership!&lt;/p&gt;
        ///&lt;p&gt;To welcome you to our community, ROYALE wants to offer you savings on your next purchase of ROYALE. &lt;a href=&quot;http://www.gocoupons.ca/27-brand-coupons-ROYALE.html&quot; target=&quot;_blank&quot;&gt;Click here&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;Have you received this message in error? To be removed from the Moment with ROYALE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoyaleBody {
            get {
                return ResourceManager.GetString("RoyaleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to momentwithroyale@royalepromotions.ca.
        /// </summary>
        internal static string RoyaleEmail {
            get {
                return ResourceManager.GetString("RoyaleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;img src=&quot;http://www.royalepromotions.ca/images/email/royale_table_bottom.jpg&quot; width=&quot;580&quot; height=&quot;28&quot; border=&quot;0&quot; alt=&quot; &quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;br /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&quot;center&quot;&gt;&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; width=&quot;560&quot;&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; width=&quot;350&quot; style=&quot;color: #444444; font-family: trebuchet ms, geneva, arial, helvetica, sans-serif; font-size: 8pt;&quot;&gt;This email was sent by: &lt;span style=&quot;font-weight: bold;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoyaleFooter {
            get {
                return ResourceManager.GetString("RoyaleFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body bgcolor=&quot;#FFFFFF&quot; style=&quot;background: #FFFFFF&quot;&gt;&lt;br /&gt;&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;580&quot; align=&quot;center&quot; bgcolor=&quot;#FFFFFF&quot; style=&quot;background: #FFFFFF&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;img src=&quot;http://www.royalepromotions.ca/images/email/moment_with_royale_header_en.jpg&quot; width=&quot;580&quot; height=&quot;151&quot; border=&quot;0&quot; alt=&quot;Moment with Royale&quot; /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;br /&gt;&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;580&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;img src=&quot;http://www.royalepromotions.ca/images/email/royale_table_top.jpg&quot; wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoyaleHeader {
            get {
                return ResourceManager.GetString("RoyaleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome from  ROYALE.
        /// </summary>
        internal static string RoyaleSubjectLine {
            get {
                return ResourceManager.GetString("RoyaleSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://royalepromotions.ca/moment/.
        /// </summary>
        internal static string RoyaleUrl {
            get {
                return ResourceManager.GetString("RoyaleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Thank you for becoming a member of the  Scotties Online Community.&lt;/strong&gt;
        ///&lt;br /&gt;&lt;br /&gt;
        ///You will soon begin receiving information, rewards and savings absolutely free. 
        ///&lt;br /&gt;&lt;br /&gt;
        ///Have you received this message in error?  To be removed from the Scotties Online Community just &lt;a href=&quot;[[ServerURL]]/Unsubscribe.aspx?email=[[uemail]]&quot;&gt;click here&lt;/a&gt;.
        ///&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string ScottiesBody {
            get {
                return ResourceManager.GetString("ScottiesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LikeNoOther@scottiespromotions.com.
        /// </summary>
        internal static string ScottiesEmail {
            get {
                return ResourceManager.GetString("ScottiesEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td align=&quot;center&quot; bgcolor=&quot;white&quot;&gt;&lt;br&gt;
        ///        &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; border=&quot;0&quot; align=&quot;center&quot; width=&quot;580&quot; bgcolor=&quot;white&quot;&gt;
        ///          &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///              &lt;td  align=&quot;left&quot; bgcolor=&quot;white&quot; style=&quot;padding-right:10px; font-family:Arial, Helvetica, sans-serif; font-size:11px;&quot;&gt;This email was sent by: Irving Consumer Products&lt;br&gt;
        ///                100 Midland Drive, Dieppe, NB E1A 6X4, Canada&lt;/td&gt;
        ///              &lt;td align=&quot;right&quot; bgcolor=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScottiesFooter {
            get {
                return ResourceManager.GetString("ScottiesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body bgcolor=&quot;white&quot; bottommargin=&quot;0&quot; topmargin=&quot;0&quot; leftmargin=&quot;0&quot; rightmargin=&quot;0&quot;&gt;&lt;br /&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot; bgcolor=&quot;white&quot;&gt;
        ///  &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///      &lt;td colspan=&quot;3&quot; bgcolor=&quot;white&quot;&gt;&lt;img src=&quot;http://scottiesfacial.com/uploadedImages/Emails/2012.04.20-scotties_heading.gif&quot; width=&quot;600&quot; height=&quot;146&quot; border=&quot;0&quot; alt=&quot;Scotties Grow The Community&quot;&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td bgcolor=&quot;white&quot;  style=&quot;font-size:14px; color:#58595b; font-weight: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScottiesHeader {
            get {
                return ResourceManager.GetString("ScottiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome from Scotties.
        /// </summary>
        internal static string ScottiesSubjectLine {
            get {
                return ResourceManager.GetString("ScottiesSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://scottiespromotions.com/.
        /// </summary>
        internal static string ScottiesUrl {
            get {
                return ResourceManager.GetString("ScottiesUrl", resourceCulture);
            }
        }
    }
}
